version: "3"
services:
  weatherapp_backend:
    build: ./backend/
    image: weatherapp_backend:2.0.0
    ports:
      - "9000:9000"
  weatherapp_frontend:
    build: ./frontend/
    image: weatherapp_frontend:2.0.0
    ports:
      - "8000:8000"
    volumes:
      - ./frontend/:/usr/src/weatherapp_frontend/:ro